### ISSUE TITLE
Todos

### ISSUE THREAD

**Issue by liorgolgher** [HagaiHargil/Multiscaler_Image_Generator#1]
1. The code fails when the number of pixels is different between X and Y. You might want to switch EdgeX with EdgeY.
2. STOP2 could use another million time bins when ScanImage is in use, as in:
   STOP2_Dataset.Time_of_Arrival = STOP2_Dataset.Time_of_Arrival + 1e6;
3. Consider replacing the following line:
           abs(sin(CurrentEvents(:, 3)));
   with:
           OffsetPhase = 0; % if necessary, add OffsetPhase as an input parameter
           CurrentEvents(:, 3) = 0.5 .\* (1 + sin(CurrentEvents(:, 3) + OffsetPhase));
4. Welcome back!
5. Add a respectable way to populate StartOfFrameVec, instead of the following two lines:
   
   ```
   NumGuessedFrames = 8;
   StartOfFrameVec = linspace(1,PhotonArray(end,2) , NumGuessedFrames+1)';
   ```
6. Line 167 should be changed from:
          PhotonArray = [PhotonArray, table2array(InterpData(:,4))];
   to:
           PhotonArray = [PhotonArray, table2array(InterpData(:,end))];

**Comment by HagaiHargil** [comment]
1. SizeX can be different from SizeY since we moved to ImageGenerationHist5.
2. Irrelevant.
3.  Not done yet.
4. Thanks.
5. Added it to GUI.
6. Changed.

In summary, only issue 3 currently remains, since TAG interpolation isn't working properly.

**Comment by HagaiHargil** [comment]
Opening a new issue for TAG interpolation. Closing this one.
